version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - medipillcheck-network

networks:
  medipillcheck-network:
    driver: bridge 